config/routes.rb
Rails.application.routes.draw do

  get '/databases/:id' => 'main#database', :as => :databases
  get '/databases/:db/:id' => 'main#table', :as => :databases_table

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  root 'main#index'

end

app/models/database.rb
class Database < ActiveRecord::Base
  
  self.table_name = "pg_database"
  self.primary_key = "datdba"
  
  # helper to check if a class exists
	def self.class_exists?(class_name)
	  eval("defined?(#{class_name}) && #{class_name}.is_a?(Class)") == true
	end

  # helper for createing a class
	def self.create_class(class_name, superclass, &block)
    klass = Class.new superclass, &block
    Object.const_set class_name, klass
  end

	#
	# Create a local table model
	#
	def self.alloc_local_table( tablename )
		puts "Create local model for #{tablename}"
		create_class( tablename.classify, ActiveRecord::Base ) do
			def self.table_name_prefix; 'trans_'; end
			def self.attributes_protected_by_default; []; end
		end if not class_exists?( tablename.classify )
	end
  
  def self.tables_for( database )
    if not Database.const_defined?( object_classify_name(database) )
      Database.module_eval <<-"EOS"
        module #{object_classify_name(database)}
          class Connect < ActiveRecord::Base
            self.table_name = "pg_database"
            self.primary_key = "datdba"
            def self.db_config
              config = ActiveRecord::Base.connection.instance_eval { @config }
              config.merge( :database => '#{database}', :pool => 1 )
            end
            establish_connection( db_config )
          end
          # self
        end
      EOS
    end
    
    #
    # establish connection to be able to get all tables
    #
    db = "Database::#{object_classify_name(database)}".constantize
    conn = "Database::#{object_classify_name(database)}::Connect".constantize.connection
    begin
      conn.tables.each do | table |
        if not db.const_defined?( "Database::#{object_classify_name(database)}::#{object_classify_name(table)}" )
          puts "* create table Database::#{database.classify}::#{table.classify}"
          #
          # we have created a Module Database::DBNAME in which we will
          # create all classes of all tables we find in database
          #
          "Database::#{object_classify_name(database)}".constantize.module_eval <<-"EOS"
            class #{object_classify_name(table)} < #{"Database::#{object_classify_name(database)}::Connect".constantize}
              self.table_name = "#{table.to_sym}"
              self.primary_key = :id
              #establish_connection( db_config )
              #connection
            end
          EOS
        end
      end
    rescue Exception => e
      puts e
    end
    "Database::#{object_classify_name(database)}".constantize.constants
  end
  
  def self.object_classify_name( name )
    name.gsub( /[-.]/, '_' ).classify
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  
  before_action :authenticate

  class Dbconnect < ActiveRecord::Base
    def self.set_table_name 
      "pg_roles"
    end
  end

  def authenticate
    authenticate_or_request_with_http_basic('Database login') do |username, password|
      config = Dbconnect.connection.instance_eval { @config }
      if username != config[:user] || !Dbconnect.connected?
        logger.debug "Connect as user: #{username}"
        Dbconnect.establish_connection(config.merge(:username => username, :password => password))
        Dbconnect.connection.execute("SELECT now()") rescue nil #force connection
      end
      login_ok = Dbconnect.connected?
      @current_user = username if login_ok
      login_ok
    end
  rescue
    false
  end

  def logout
    @realm = 'Login Required'
    response.headers["Status"] = "Unauthorized"
    response.headers["WWW-Authenticate"] = "Basic realm=\"#{@realm}\""
    render :text => '', :status => 401
  end

  def current_user
    @current_user ||= nil
  end

  private
  
  def db_schema_tables_select
    if params[:database_name]
      @database = Database.find_by_name(params[:database_name])
      params[:schema_name] ||= 'public'
      @db_schema = @database.find_schema_by_name(params[:schema_name])
      @tables = @db_schema.tables
    end
  end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    @databases = Database.all
  end

  def database
    @database = params[ :id ]
    @tables = Database.tables_for( params[ :id ] )
  end

  def table
    @database = params[ :db ]
    @table = params[ :id ]
    puts "--------------------------"
    puts "Database::#{Database.object_classify_name(@database)}::#{Database.object_classify_name(@table)}"

    @tables = Database.tables_for( params[ :db ] )
    @rows = "Database::#{Database.object_classify_name(@database)}::#{Database.object_classify_name(@table)}".constantize.page( params[ :page ] ).per( 10 )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postview</title>
	<link href='http://fonts.googleapis.com/css?family=Nunito:400,700,300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-default navbar-fixed" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
			<%= link_to "Admin", root_path, :class => 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse">
			<% if true #admin_logged_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to '<i class="glyphicon-class glyphicon glyphicon-th-list"></i> Product'.html_safe %></li>
        <li><%= link_to '<i class="glyphicon-class glyphicon glyphicon-user"></i> Customer'.html_safe %></li>
        <li><%= link_to '<i class="glyphicon-class glyphicon glyphicon-th"></i> Basket'.html_safe %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon-class glyphicon glyphicon-cog"></i> System <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to '<i class="glyphicon-class glyphicon glyphicon-tags"></i> Currency'.html_safe %></li>
            <li class="divider"></li>
            <li><%= link_to '<i class="glyphicon-class glyphicon glyphicon-user"></i> Admin'.html_safe %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
				<li><%= link_to '<i class="glyphicon-class glyphicon glyphicon-log-out"></i> Logout'.html_safe %></li>
      </ul>
			<% end %>
    </div>
  </div>
		
  <div class="container">
		
		<%#= render 'layouts/backend/messages' %>
		<%= yield %>
		
	</div>

</body>
</html>

app/views/main/database.html.erb
<h1>Tables for <%= @database %></h1>

<%#= debug @tables %>

<div>
  <ul>
  <% @tables.each do | table | %>
    <% tab = "Database::#{Database.object_classify_name(@database)}::#{table.to_s}".constantize %>
    <li><%= link_to tab.table_name.classify, databases_table_path( @database, tab.table_name ) %></li>
  <% end %>
  </ul>
</div>

app/views/main/index.html.erb
<h1>Databases</h1>

<div>
  <ul>
  <% @databases.each do | database | %>
    <li><%= link_to database.datname, databases_path( database.datname ) %></li>
  <% end %>
  </ul>
</div>

app/views/main/table.html.erb
<h3>Data for <%= @database %> and <%= @table %></h3>

<%#= debug @rows %>

<% if @rows.size > 0 %>
<div class="rows">
  <table class="table">
    <thead>
      <tr>
        <% @rows.first.attributes.each do | field | %>
        <th><%= field.first %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @rows.each do | row | %>
      <tr>
        <% row.attributes.each do | field | %>
        <td><%= field.last %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= paginate @rows %>

<br>

<% end %>